### ISSUE TITLE
Unable to use ID for target release & definition parameters

### ISSUE THREAD

**Issue by keithpatton** [dmitryserbin/azdev-release-orchestrator#51]
When upgrading from v1 to v2 i noticed that when using Specific Release option it is not possible to supply the specific ReleaseID, it fails saying not found. We supply the specific release via a variable which corresponds to the unique release ID, so are unable to upgrade for the specific release scenario. 

Also, when specifying release definition, we had switched to using IDs for v1 and now it appears only to accept the Name, this means if the name of the releae definition changes through an edit it could fail. 

would be good in all circumstances to allow specific ids for specific releases and definitions.

**Comment by dmitryserbin** [comment]
Thanks for the feedback. V2 uses names all the way, you may need to update your variables to release and definition names instead of IDs.

I will see if it's possible to add ID support in future. It's not very straightforward as I have to use different mechanisms to target release or definition based name or ID values (due to Azure DevOps API limitations).

**Comment by keithpatton** [comment]
Not a problem, we've updated to using Release Definition Names and Release Names already.

**Comment by dmitryserbin** [comment]
Cool, it'a more convenient way, specially from readability perspective in YAML files.
